### ISSUE TITLE
datalens-temporal container unhealth - log "fork: retry: Resource temporarily unavailable" into docker-compose.production.yaml сontainer

### ISSUE THREAD

**Issue by DGDarkKing** [datalens-tech/datalens#324]
Добрый день
Подскажите пожалуйста, что такое datalens-temporal

Почему может возникнуть ситуация, когда он перестаёт работать - работал 6 дней нормально, потом перестал работать
посмотрел контейнеры у него стоит флаг unhealth, после перезапуска заработал нормально, но хотелось бы понять, как предотвратить снова такую проблему

Описание сeрвиса (стандартное после создания docker-compose.production.yaml)

```
temporal:
    container_name: datalens-temporal
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    environment:
      NAMESPACES: meta-manager
      POSTGRES_DB: pg-temporal-db
      POSTGRES_DB_VISIBILITY: pg-temporal-visibility-db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${LOCAL_PG_PASSWORD}
      POSTGRES_PORT: "5432"
      POSTGRES_USER: pg-user
      TEMPORAL_AUTH_ENABLED: "true"
      TEMPORAL_AUTH_PRIVATE_KEY: ${SECRET_ONE}
      TEMPORAL_AUTH_PUBLIC_KEY: ${SECRET_TWO}
    healthcheck:
      test:
        - CMD
        - /etc/temporal/healthcheck.sh
      interval: 5s
      retries: 10
      start_period: 3s
    image: ghcr.io/datalens-tech/datalens-temporal:1.27.2
    networks:
      default: null
    pull_policy: always
```

Несколько последних логов до перезапуска (не уверен даст ли это информации поскольку первое упоминание "fork: retry: Resource temporarily unavailable" было 4 дня назад, т.е. двое суток работало без этого сообщения, но через сутки выдавало это сообщение каждый день. Но до сегодняшнего дня его выдавало 1-5 раз и всё продолжало работать нормально, вроде как, поскольку никто не жаловался, а сегодня данное сообщение вывелось примерно 401 раз)
```
datalens-temporal  | 2025-06-04T06:30:25.851782327Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:30:26.852272252Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:30:32.098462973Z {"level":"info","ts":"2025-06-04T06:30:32.097Z","msg":"Started physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/clear-expired-queue/1","wf-task-queue-type":"Workflow","wf-namespace":"meta-manager","worker-build-id":"_unversioned_","lifecycle":"Started","cause":"Poll","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:194"}
datalens-temporal  | 2025-06-04T06:31:09.623794569Z {"level":"info","ts":"2025-06-04T06:31:09.623Z","msg":"Stopped physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/default-worker-tq/3","wf-task-queue-type":"Workflow","wf-namespace":"temporal-system","worker-build-id":"_unversioned_","lifecycle":"Stopped","cause":"Idle","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:212"}
datalens-temporal  | 2025-06-04T06:31:25.851257435Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:31:26.851566558Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:32:25.851247472Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:32:26.852945992Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:33:25.851336989Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:33:26.851628587Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:34:25.850759831Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:34:26.851215073Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:35:04.661633539Z {"level":"info","ts":"2025-06-04T06:35:04.661Z","msg":"Started physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/default-worker-tq/3","wf-task-queue-type":"Workflow","wf-namespace":"temporal-system","worker-build-id":"_unversioned_","lifecycle":"Started","cause":"Poll","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:194"}
datalens-temporal  | 2025-06-04T06:35:25.852680609Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:35:26.853112594Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:36:25.851291525Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
datalens-temporal  | 2025-06-04T06:36:26.851720741Z /etc/temporal/init-temporal.sh: fork: retry: Resource temporarily unavailable
```
